FROM ubuntu:20.04

#Se instala ansible y sshpass
RUN apt-get update && apt-get install -y ansible sshpass openssh-server
RUN mkdir /var/run/sshd
#Se habilita archivo inventario
RUN sed -i 's|#inventory      = /etc/ansible/hosts|inventory=/etc/ansible/hosts|' /etc/ansible/ansible.cfg

#Se agrega dns contenedores ubuntu ssh a hosts ansible
RUN echo 'ubuntu_ssh1\nubuntu_ssh2\nubuntu_ssh3' >>/etc/ansible/hosts

#Se genera llave ssh
RUN ssh-keygen -q -t rsa -N ' ' -f /root/.ssh/id_rsa

#Se copia playbook desde local hacia contenedor ansible
COPY playdesa3.yml /root/playdesa3.yml
WORKDIR /root
CMD ["/usr/sbin/sshd", "-D"]
